#!/usr/bin/python

import dbus, sys

notify = dbus.SessionBus().get_object('org.kde.knotify','/Notify')

title, message = sys.argv[1:3]

notify.event('warning','kde',[],title,message,[],[],0,0,dbus_interface='org.kde.KNotify')
